import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
      className={`${geistSans.variable}" m-0 p-0" 
      ${geistMono.variable} antialiased`}>
      <nav className=" bg-red-700 items-center justify-center h-14 p-3">
        <ul className="flex gap-10 justify-center text-center items-center font-mono">
          <li className="text-mono cursor-pointer">Home</li>
          <li className="text-mono cursor-pointer">Contact</li>
          <li className="text-mono cursor-pointer">About</li>
        </ul>
      </nav>
        {children}
        <footer className="bg-red-700 items-center text-center justify-center flex h-14">
          <p>Created By Fiky Alrasya 17-01-2025</p>
        </footer>
      </body>
    </html>
  );
}
